dist: trusty
sudo: required
language: cpp
compiler: gcc
before_install:
    - sudo apt-get -qq update
install: sudo apt-get install -y cmake libboost-filesystem-dev libboost-system-dev libboost-regex-dev
script:
    - cmake . && cmake --build .
    - bin/testproject
